### ISSUE TITLE
Retard + J'ai fait n'importe quoi avec git...

### ISSUE THREAD

**Issue by axbator28** [PolytechLyon/isi3-tp4-kebab-kata-isi3-tp4-pittore-kebab-kata#1]
Pour l'instant, j'ai encore le tp dans l'état auquel je l'avais laissé la séance, car j'ai été pris par un projet. Je compte le finir ce week end. Mais déjà, je vais essayer de résoudre le problème que j'ai réussi à me créer avec git. 
Désolé pour le dérangement

**Comment by k33g** [comment]
bonjour @axbator28, vous avez une visibilité sur le moment où vous aurez fini?

**Comment by axbator28** [comment]
Je l'aurais fini demain normalement ! Désolé pour le retard de la réponse

**Comment by axbator28** [comment]
Demain étant aujourd'hui finalement

**Comment by k33g** [comment]
Bonsoir
Le rapport est beaucoup trop léger
Il n'y a pas de code de test dans le Main du composite

**Comment by axbator28** [comment]
Hello,
J'ai rajouté le code du composite.
Pour le rapport, j'ai décrit le code (je ne crois pas que c'était ce qui est demandé) et rajouté quelque informations sur les patterns.
Bon week end !
